name: Run Naveen Cypress Tests
on: push

env:
   CYPRESS_EMAIL: ${{secrets.CYPRESS_EMAIL}}
   CYPRESS_PASSWORD: ${{secrets.CYPRESS_PASSWORD}}

jobs:
   cypress-run:
      runs-on: ubuntu-latest
      steps:
         - name: Checkout
           uses: actions/checkout@v3
           # install any NPM dependencies like plugins, etc.
         - name: Cyress Install
           run: npm install --legacy-peer-deps
         # install cypress steps - maintained by cypress.io
         # do not run cypress tests during the install
         - name: Cypress Run
           uses: cypress-io/github-action@v5
           with:
              install: false
              config-file: cypress.config.ts
              browser: chrome
              headed: true